language: java
jdk:
  - oraclejdk8

env:
  global:
    - GH_REF: github.com/hvpaiva/java-padroes-projeto.git

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# default install command is just "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e

after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=hvpaiva_java-padroes-projeto -Dsonar.organization=hvpaiva-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  - bash update-ghpages.sh

# use latest java version available instead of travis default
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    - high.v.paiva@gmail.com

sudo: required